-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 10:51:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maquina_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maquina_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maquina_test` DEFAULT CHARACTER SET utf8 ;
USE `maquina_test` ;

-- -----------------------------------------------------
-- Table `maquina_test`.`vidrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maquina_test`.`vidrio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MAC` VARCHAR(45) NULL,
  `total` INT NULL,
  `parcial` INT NULL,
  `offset` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;